### ISSUE TITLE
ToC not showing

### ISSUE THREAD

**Issue by danielsarj** [danielsarj/spotify#1]
Note for future self: the Table of Contents isn't showing up on my HTML page when opening with `http://htmlpreview.github.io/`. Not sure how to fix it right now. When I knit the .Rmd file in my local Rstudio, it works. 

Rmarkdown code that implements ToC:
```
output: 
  html_document:
    toc: true
    toc_float: true
```
